services:
  mongo:
    container_name: database
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
  deno-server:
    container_name: server
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
    command: "deno task watch"

volumes:
  mongo-data: